### ISSUE TITLE
parameters with underbars `_` not supported

### ISSUE THREAD

**Issue by dbainbri-ciena** [YoshiyukiKato/grpc-mock#11]
I am attempting to return an ENUM value as part of an output. I have tried both specifying the value as its string representation as well as its integer representation, but neither seems to be working. Should this work?

**Comment by dbainbri-ciena** [comment]
This could actually be an issue with a "nested" message specification in the output as well.

simplified:
```
message Config {
   SomeEnumType value;
}

message Response {
  string name = 1 ;
  Config myconfig = 2 ;
}
```
specified as output as `output: { name: "somevalue", myconfig: { value: <v> }}`

**Comment by dbainbri-ciena** [comment]
ok, more details, it may be an issue with fields that have an underbar '_' in them ...

**Comment by dbainbri-ciena** [comment]
Confirmed with the following sample proto (changes to the default greeter)
```
syntax="proto3";

package greeter;

service Greeter {
  rpc Hello (RequestGreet) returns (ResponseGreet) {}
  rpc Goodbye (RequestGreet) returns (ResponseGreet) {}
  rpc HowAreYou (stream RequestGreet) returns (ResponseGreet) {}
  rpc NiceToMeetYou (RequestGreet) returns (stream ResponseGreet) {}
  rpc Chat (stream RequestGreet) returns (stream ResponseGreet) {}
}

message RequestGreet {
  string message = 1;
  string extra_data = 2;
  string more = 3;
}

message ResponseGreet {
  string message = 1;
  string something_else = 2;
  string evenmore = 3;
}
```

**Comment by dbainbri-ciena** [comment]
Pilot error. Needed to have the proto loader option `keepCase: true`.

**Comment by William-Yeh** [comment]
I encounter the same issue that underscore_separated_names for field names are totally ignored.

According to [Protobuf Style Guide](https://developers.google.com/protocol-buffers/docs/style#message-and-field-names):

> **Message and field names**
> Use underscore_separated_names for field names (including oneof field and extension names) – for example, song_name.

Do you consider to support the underscore_separated_names as well?

Thanks.
