### ISSUE TITLE
support grpc errors

### ISSUE THREAD

**Issue by jkryl** [YoshiyukiKato/grpc-mock#4]
Thanks for the great package! Is there a plan to support returning gRPC errors from the mock server? Something like:
```
  rules: [
    {
      method: "howAreYou",
      input: { message: "Hi" },
      error: {
         code: 5,
         message: "Resource not found",
         data: ... (optional custom data),
    },
```
That would be quite useful for me..

**Comment by YoshiyukiKato** [comment]
@jkryl 
Thank you for question!
I'm sorry for I have never plan to return gRPC error from mock server...

But, I agree with you. That is very useful feature.
I will think how to implement it. If you have any ideas, please let me know!

**Comment by aborovsky** [comment]
First step to implement this feature: https://github.com/YoshiyukiKato/grpc-mock/pull/6

**Comment by YoshiyukiKato** [comment]
@jkryl Hi! Simple error response support #6 (by @aborovsky) is merged and new version has been published to npm. Please check it out when it is convenient for you.

**Comment by jkryl** [comment]
It works for me. thanks! 👍
