### ISSUE TITLE
Wrong behaviour: callback not being called if no rule match the input

### ISSUE THREAD

**Issue by aborovsky** [YoshiyukiKato/grpc-mock#9]
The case: currently implementation for each request looks though rules at https://github.com/YoshiyukiKato/grpc-mock/blob/master/index.js#L67 and trying to find corresponding rule and output.

If no rule was found, then callback not being called at all. And no exception was raised.
As result current test running process just get stuck (mocha, jest test runner, for example). And you have no idea what's going wrong. Cause your grpc client code expects a ccallback from GRPC at any case. But grpc-mock will not call it in that case.

As a developer, i have only one way out: set a breakpoint at grpc-mock's for loop and find wrong request, that was not able to find proper rule. It'a a headache.

Propose to change the behaviour: if no rules was matched current request, rais an exception.
Similar logic implemented at nock library: https://github.com/nock/nock#expectations

**Comment by ignatov357** [comment]
+1

**Comment by YoshiyukiKato** [comment]
@aborovsky Thank you for your propose. You are completely right. I overlooked that point. I will implement the feature in 2-3 days.

**Comment by YoshiyukiKato** [comment]
Hi! I implemented the feature to throw error when an input does not match any rules. I released it as ver 0.6.0 onto npm. Please try it out and tell me your feedbacks. Thank you :)

**Comment by aborovsky** [comment]
Sorry for no response. It works great! Thanks a lot.
